Repository OZ-Coding-School/oz_03_collabo-005-FE, pull requests merged in 2024-09, with the labels that each got.

#23 ✨ Feat: myprofile api 데이터 연결
  src/components/board/BoardCard.tsx
  src/components/landing/FoodSection.tsx
  src/components/landing/FoodsCarousel.tsx
  src/components/landing/ImageWithPlaceHolder.tsx
  src/components/myprofile/UserInfo.tsx
  src/components/thunder/ThunderCard.tsx
  src/pages/board/Board.tsx
  src/pages/flavor/FlavorTest.tsx
  src/pages/myprofile/MyProfile.tsx
  src/pages/myprofile/MyProfileBoard.tsx
  src/pages/myprofile/MyProfileEdit.tsx
  src/pages/myprofile/MyProfileThunder.tsx
  src/pages/profile/ProfileId.tsx
  src/pages/thunder/Thunder.tsx
  src/types/types.ts
Labels: ✨ Feat, 🎨 Design, 🔥 Edit

#24 ✨ Feat: thunder 카테고리 api데이터로 동작하도록 수정
  src/data/FoodsCarouselList.ts
  src/pages/myprofile/MyProfileEdit.tsx
  src/pages/thunder/Thunder.tsx
Labels: ✨ Feat, 🔥 Edit

#25 📦️ Chore: S3-CloudFront CICD Settings
  .github/deploy.yml
  index.html
  src/components/thunder/ThunderClockModal.tsx
  src/pages/board/Board.tsx
  src/pages/board/BoardId.tsx
  src/pages/board/BoardPost.tsx
  src/pages/thunder/Thunder.tsx
  src/pages/thunder/ThunderChat.tsx
  src/pages/thunder/ThunderId.tsx
  src/pages/thunder/ThunderPost.tsx
  vite.config.ts
Labels: ✨ Feat, 🎨 Design, 📦 Chore, 🔥 Edit

#27 ✨ Feat: myprofile 수정 기능
  src/App.tsx
  src/api/util/instance.ts
  src/components/common/ModalCenter.tsx
  src/components/landing/FirstSection.tsx
  src/components/landing/FoodSection.tsx
  src/components/landing/FoodsCarousel.tsx
  src/components/myprofile/FTILink.tsx
  src/components/myprofile/LoadingSpinner.tsx
  src/components/myprofile/ProfileForm.tsx
  src/components/myprofile/ProfileImageInput.tsx
  src/components/myprofile/ProfileImageSection.tsx
  src/components/myprofile/UserLink.tsx
  src/pages/Home/Landing.tsx
  src/pages/board/Board.tsx
  src/pages/board/BoardPost.tsx
  src/pages/myprofile/MyProfile.tsx
  src/pages/myprofile/MyProfileBoard.tsx
  src/pages/myprofile/MyProfileEdit.tsx
  src/pages/myprofile/MyProfileThunder.tsx
  src/pages/profile/ProfileId.tsx
  src/pages/terms/Terms.tsx
  src/pages/thunder/Thunder.tsx
  src/pages/thunder/ThunderPost.tsx
Labels: ✨ Feat, ♻️ Refactor, 🔧 Change

#28 ✨ Feat: introuduction page 생성
  package-lock.json
  package.json
  src/App.tsx
  src/components/board/BoardCard.tsx
  src/components/landing/FoodsCarousel.tsx
  src/components/layout/Header.tsx
  src/components/layout/Nav.tsx
  src/components/myprofile/UserInfo.tsx
  src/pages/flavor/FlavorTest.tsx
  src/pages/introduction/Introduction.tsx
  src/pages/introduction/index.tsx
  src/pages/myprofile/MyProfile.tsx
  src/pages/myprofile/MyProfileEdit.tsx
  src/types/types.ts
Labels: ✨ Feat, 🔥 Edit

#29 ✨ Feat: NotFound page 생성
  public/images/404.svg
  src/App.tsx
  src/components/common/Image.tsx
  src/components/layout/Header.tsx
  src/components/layout/HeaderLanding.tsx
  src/components/thunder/ThunderCard.tsx
  src/pages/board/BoardId.tsx
  src/pages/introduction/Introduction.tsx
  src/pages/notfound/NotFound.tsx
  src/pages/notfound/index.tsx
  src/pages/thunder/ThunderId.tsx
Labels: 🐛 Fix, ✨ Feat, 🔥 Edit

#30 ✨ Feat: sitemap 설정
  public/robots.txt
  public/sitemap.xml
Labels: ✨ Feat

#31 🔥 Edit: 로봇파일의 주소 경로 오타 수정
  public/robots.txt
Labels: 🔥 Edit

#32 📦️ Chore: S3-CloudFront CICD Settings 수정
  index.html
  public/images/babpiens_favicon.svg
  public/images/babpiens_logo.svg
  src/components/foods/FoodCard.tsx
  src/components/layout/HeaderLanding.tsx
  src/components/thunder/ThunderCard.tsx
  src/components/thunder/ThunderClockModal.tsx
  src/components/thunder/ThunderImageModal.tsx
  src/data/FoodsCarouselList.ts
  src/pages/board/Board.tsx
  src/pages/board/BoardId.tsx
  src/pages/board/BoardPost.tsx
  src/pages/thunder/ThunderId.tsx
  src/pages/thunder/ThunderPost.tsx
Labels: 🐛 Fix, ✨ Feat, 🔧 Change, 📦 Chore, 🔥 Edit

#33 🔧 Change: Fti 파일명 변경
  src/pages/fti/Fti.tsx
  src/pages/fti/FtiResultId.tsx
  src/pages/fti/FtiTest.tsx
Labels: 🔧 Change

#34 ✨ Feat: Fti 검사 구현
  index.html
  public/images/foodsPotato.png
  public/images/ftiResult.png
  public/images/ftiStart.png
  public/images/ftiTest.png
  public/images/insta.png
  public/images/kakaotalk.png
  public/images/kimchi.png
  public/images/share.png
  public/images/snsX.png
  src/App.tsx
  src/DUMMY_DATA/FOOD_DATA.json
  src/api/apis/auth.ts
  src/api/apis/foods.ts
  src/api/apis/fti.ts
  src/api/services/ftiService.ts
  src/components/auth/.gitkeep
  src/components/common/Button.tsx
  src/components/foods/FoodCard.tsx
  src/components/foods/KakaoMap.tsx
  src/components/landing/FoodsCarousel.tsx
  src/components/layout/Header.tsx
  src/components/layout/Nav.tsx
  src/data/ftiAnswer.json
  src/pages/.gitkeep
  src/pages/auth/Signin.tsx
  src/pages/auth/Signup.tsx
  src/pages/foods/Foods.tsx
  src/pages/foods/FoodsId.tsx
  src/pages/foods/FoodsMap.tsx
  src/pages/foods/index.tsx
  src/pages/fti/Fti.tsx
  src/pages/fti/FtiResultId.tsx
  src/pages/fti/FtiTest.tsx
  src/store/.gitkeep
  src/store/foodStore.ts
  src/types/.gitkeep
  src/types/ftiTypes.ts
Labels: 🐛 Fix, ✨ Feat, ♻️ Refactor, 🔧 Change, 📦 Chore, 🔥 Edit

#35 ✨ Feat: fti 테스트 저장하는 api 적용
  src/components/common/ModalBottom.tsx
  src/components/common/ModalCenter.tsx
  src/components/landing/FoodsCarousel.tsx
  src/components/layout/Nav.tsx
  src/components/myprofile/UserInfo.tsx
  src/components/myprofile/UserLink.tsx
  src/data/BoardList.tsx
  src/data/flavorTest.ts
  src/data/reviewList.ts
  src/pages/flavor/Flavor.tsx
  src/pages/flavor/FlavorTest.tsx
  src/pages/myprofile/MyProfile.tsx
  src/pages/myprofile/MyProfileEdit.tsx
  src/pages/thunder/Thunder.tsx
  src/store/store.ts
  src/types/types.ts
  tailwind.config.js
Labels: ✨ Feat, 🎨 Design, ♻️ Refactor, 🔧 Change

#37 🎨 Design: myprofile thunder / board swiper로 구현
  src/components/myprofile/BoardList.tsx
  src/components/myprofile/PostNav.tsx
  src/components/myprofile/ThunderList.tsx
  src/pages/myprofile/MyProfileBoard.tsx
  src/pages/myprofile/MyProfileThunder.tsx
Labels: 🎨 Design

#38 ♻️ Refactor: fti결과페이지 리팩토링
  src/api/apis/foods.ts
  src/api/apis/fti.ts
  src/pages/foods/Foods.tsx
  src/pages/fti/Fti.tsx
  src/pages/fti/FtiResultId.tsx
  src/pages/fti/FtiTest.tsx
  src/utils/shareUtils.ts
  src/utils/storage.ts
Labels: ✨ Feat, 🎨 Design, ♻️ Refactor, 🔥 Edit

#39 🐛 Fix: build시 error해결
  src/api/apis/auth.ts
  src/pages/auth/Signin.tsx
  src/pages/fti/FtiTest.tsx
Labels: 🐛 Fix

#40 🐛 Fix: 음식 중복 제거
  src/pages/foods/Foods.tsx
Labels: 🐛 Fix

#41 🔥 Edit: 로컬스토리지 저장 값 변경
  src/pages/fti/FtiTest.tsx
Labels: 🔥 Edit

#42 ✨ Feat: 소셜 다이닝 소통방, 모임 기능 추가
  index.html
  src/components/board/BoardComments.tsx
  src/components/thunder/ThunderCard.tsx
  src/pages/board/BoardId.tsx
  src/pages/board/BoardPost.tsx
  src/pages/thunder/ThunderChat.tsx
  src/pages/thunder/ThunderId.tsx
  src/pages/thunder/ThunderPost.tsx
Labels: ✨ Feat, 🎨 Design, ♻️ Refactor, 🔥 Edit

#43 ✨ Feat: fti 타입 저장 기능 생성
  src/components/landing/FoodsCarousel.tsx
  src/components/myprofile/UserInfo.tsx
  src/pages/Home/Landing.tsx
  src/pages/myprofile/MyProfile.tsx
Labels: ✨ Feat, 🔥 Edit

#44 🎨 Design: 소셜 다이닝 글 쓰기 작성 카테고리 디자인 변경
  src/pages/board/Board.tsx
  src/pages/board/BoardPost.tsx
  src/pages/thunder/ThunderPost.tsx
Labels: 🎨 Design

#46 ✨ Feat: fti 테스트 이미지 추가
  src/api/apis/auth.ts
  src/api/apis/fti.ts
  src/api/services/ftiService.ts
  src/components/foods/KakaoMap.tsx
  src/pages/auth/Signin.tsx
  src/pages/foods/Foods.tsx
  src/pages/foods/FoodsId.tsx
  src/pages/fti/FtiResultId.tsx
  src/pages/fti/FtiTest.tsx
  src/types/ftiTypes.ts
Labels: ✨ Feat, 🔥 Edit

#47 🐛 Fix: 미사용변수 제거거
  src/pages/fti/FtiResultId.tsx
  src/pages/fti/FtiTest.tsx
Labels: 🐛 Fix

#48 🔥 Edit: 소셜 다이닝 페이지 기능 수정
  public/images/bobpience_logo2.png
  src/components/board/BoardCommentModal.tsx
  src/pages/thunder/Thunder.tsx
  src/pages/thunder/ThunderChat.tsx
  src/pages/thunder/ThunderId.tsx
  src/pages/thunder/ThunderPost.tsx
Labels: 🐛 Fix, 🔧 Change, 🔥 Edit

#49 🔥 Edit: 검색 엔진 sitemap, favicon 수정
  index.html
  public/images/favicon.svg
  public/sitemap.xml
  src/components/board/BoardCard.tsx
  src/components/layout/Header.tsx
Labels: 🔧 Change, 🔥 Edit
