Repository OZ-Coding-School/oz_03_collabo-005-FE, pull requests merged in 2024-08, with the labels that each got.

#1 ✨ Feat: button 기능 개발
  src/App.tsx
Labels: enhancement

#2 ✅ Test: 버튼 추가 테스트
  src/App.tsx
Labels: enhancement

#3 📝 Docs: PR템플릿 수정
  .github/ISSUE_TEMPLATE/pull_request_template.md
  .github/pull_request_template.md
  index.html
  public/vite.svg
  src/App.tsx
  src/assets/react.svg
Labels: 📝 Docs, 🔧 Change, 📦 Chore

#4 ✨ Feat: 라우터 설정
  .eslintrc.json
  package-lock.json
  package.json
  src/App.tsx
  src/components/auth/.gitkeep
  src/components/common/.gitkeep
  src/components/layout/Header.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Nav.tsx
  src/main.tsx
  src/pages/Home/Home.tsx
  src/pages/Home/Landing.tsx
  src/pages/Home/index.tsx
  src/pages/auth/ResetPassword.tsx
  src/pages/auth/Signin.tsx
  src/pages/auth/Signup.tsx
  src/pages/auth/index.tsx
  src/pages/board/Board.tsx
  src/pages/board/BoardCommentEdit.tsx
  src/pages/board/BoardId.tsx
  src/pages/board/BoardPost.tsx
  src/pages/board/index.tsx
  src/pages/flavor/Flavor.tsx
  src/pages/flavor/FlavorTest.tsx
  src/pages/flavor/index.tsx
  src/pages/foods/Foods.tsx
  src/pages/foods/FoodsId.tsx
  src/pages/foods/FoodsMap.tsx
  src/pages/foods/index.tsx
  src/pages/fti/FTI.tsx
  src/pages/fti/FTIResultId.tsx
  src/pages/fti/FTITest.tsx
  src/pages/fti/index.tsx
  src/pages/myprofile/MyProfile.tsx
  src/pages/myprofile/MyProfileBoard.tsx
  src/pages/myprofile/MyProfileEdit.tsx
  src/pages/myprofile/MyProfileThunder.tsx
  src/pages/myprofile/index.tsx
  src/pages/profile/ProfileId.tsx
  src/pages/terms/Terms.tsx
  src/pages/thunder/Thunder.tsx
  src/pages/thunder/ThunderChat.tsx
  src/pages/thunder/ThunderId.tsx
  src/pages/thunder/ThunderPost.tsx
  src/pages/thunder/index.tsx
  src/styles/global.css
Labels: 📝 Docs, ✨ Feat, 🎨 Design, 🔧 Change, 📦 Chore

#5 ✨ 로그인, 회원가입, 비밀번호 변경 페이지 제작
  .eslintrc.json
  package-lock.json
  package.json
  src/App.tsx
  src/components/common/.gitkeep
  src/components/common/Button.tsx
  src/components/common/Input.tsx
  src/pages/auth/ResetPassword.tsx
  src/pages/auth/Signin.tsx
  src/pages/auth/Signup.tsx
  src/pages/fti/FTI.tsx
  src/pages/fti/FTIResultId.tsx
  src/pages/fti/FTITest.tsx
  src/pages/fti/index.tsx
  src/styles/global.css
  tailwind.config.js
Labels: 🐛 Fix, 📝 Docs, ✨ Feat, 🎨 Design, 📦 Chore

#6 ✨ Feat: 프로필 확인 페이지 생성
  public/images/anonymous_avatars.svg
  public/images/edit_pencil.svg
  src/components/myprofile/UserInfo.tsx
  src/components/myprofile/UserLink.tsx
  src/pages/myprofile/MyProfile.tsx
  src/pages/myprofile/MyProfileBoard.tsx
  src/pages/myprofile/MyProfileEdit.tsx
  src/pages/myprofile/MyProfileThunder.tsx
  src/store/store.ts
  src/types/types.ts
  tailwind.config.js
Labels: ✨ Feat, 🎨 Design, 🔧 Change

#8 ♻️ Refactor: Landing 페이지 리팩토링
  index.html
  package-lock.json
  public/images/CuteEgg.svg
  public/images/DeliciousFinder.svg
  public/images/DeliciousInFinder.svg
  public/images/Home.svg
  public/images/HomeExample.svg
  public/images/HomeInactive.svg
  public/images/HomeMonkey.svg
  public/images/LogoInstagram.svg
  public/images/ProfileActive.svg
  public/images/ProfileInactive.svg
  public/images/SocialDining.svg
  public/images/SocialDiningActive.svg
  src/components/common/ModalBottom.tsx
  src/components/common/ModalCenter.tsx
  src/components/layout/Header.tsx
  src/components/layout/HeaderLanding.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Nav.tsx
  src/pages/Home/Landing.tsx
  src/pages/flavor/Flavor.tsx
Labels: ✨ Feat, ♻️ Refactor, 🔧 Change, 📦 Chore

#9 ✨ Feat: profile image 크롭 기능 추가
  package-lock.json
  package.json
  src/components/myprofile/ProfileModal.tsx
  src/components/myprofile/UserLink.tsx
  src/pages/myprofile/MyProfile.tsx
  src/pages/myprofile/MyProfileEdit.tsx
Labels: ✨ Feat, 🎨 Design, 📦 Chore

#10 ✨ Feat: 소셜다이닝(구번개)의 목록 기능 추가
  package-lock.json
  package.json
  public/images/CryingEgg.svg
  public/images/plusCircle.svg
  src/components/common/ModalBottom.tsx
  src/components/layout/Header.tsx
  src/components/layout/HeaderLanding.tsx
  src/components/layout/Layout.tsx
  src/components/myprofile/UserInfo.tsx
  src/components/thunder/ThunderCard.tsx
  src/data/meetingList.ts
  src/pages/thunder/Thunder.tsx
  src/styles/global.css
Labels: ✨ Feat, 🎨 Design, 🔧 Change, 📦 Chore

#11 ✨ Feat: myprofile 나의 글 목록 확인 기능 추가
  public/images/CommentIcon.svg
  src/components/board/BoardCard.tsx
  src/components/myprofile/PostNav.tsx
  src/components/myprofile/ProfileModal.tsx
  src/components/thunder/Badge.tsx
  src/components/thunder/RoundedButton.tsx
  src/components/thunder/SelectionItem.tsx
  src/components/thunder/ThunderCard.tsx
  src/data/reviewList.ts
  src/pages/myprofile/MyProfileBoard.tsx
  src/pages/myprofile/MyProfileEdit.tsx
  src/pages/myprofile/MyProfileThunder.tsx
  src/pages/thunder/Thunder.tsx
Labels: ✨ Feat, ♻️ Refactor, 🔧 Change, 🔥 Edit

#12 ✨ Feat: 프로필 자세히보기 페이지 추가
  public/images/forkknife.svg
  public/images/jewelry.svg
  src/App.tsx
  src/components/common/Image.tsx
  src/components/layout/Header.tsx
  src/components/layout/Nav.tsx
  src/components/myprofile/PostNav.tsx
  src/components/myprofile/UserInfo.tsx
  src/pages/Image/ImageOverview.tsx
  src/pages/myprofile/MyProfile.tsx
  src/pages/myprofile/MyProfileThunder.tsx
  src/pages/profile/ProfileId.tsx
Labels: ✨ Feat, 🔧 Change, 🔥 Edit

#13 ✨ Feat: ThunderPost 페이지 기능 추가
  package-lock.json
  package.json
  public/images/SocialDiningLike.svg
  public/images/SocialDiningLikeActive.svg
  public/images/ThunderCalender.svg
  public/images/ThunderCalender2.svg
  public/images/ThunderImageUpdate.svg
  public/images/maratang.svg
  src/components/layout/Header.tsx
  src/components/layout/HeaderLanding.tsx
  src/components/layout/Nav.tsx
  src/components/thunder/ThunderCalendarModal.tsx
  src/components/thunder/ThunderClockModal.tsx
  src/pages/Home/Landing.tsx
  src/pages/flavor/Flavor.tsx
  src/pages/thunder/ThunderId.tsx
  src/pages/thunder/ThunderPost.tsx
Labels: ✨ Feat, 🔧 Change, 📦 Chore, 🔥 Edit

#14 ✨ Feat: Thunder 상세 정보 페이지 기능 추가
  src/components/thunder/ThunderCalendarModal.tsx
  src/pages/Home/Landing.tsx
  src/pages/thunder/ThunderId.tsx
Labels: ✨ Feat, 🎨 Design, 🔥 Edit

#15 ✨ Feat: 입맛검사 ui와 기능 생성
  public/images/leftArrow.svg
  public/images/openMouseEgg.svg
  public/images/rightArrow.svg
  src/App.tsx
  src/components/flavor/ProgressBar.tsx
  src/components/layout/Header.tsx
  src/components/layout/HeaderLanding.tsx
  src/components/layout/Layout.tsx
  src/components/layout/Nav.tsx
  src/components/thunder/Badge.tsx
  src/data/flavorTest.ts
  src/pages/Home/Home.tsx
  src/pages/Home/Landing.tsx
  src/pages/flavor/Flavor.tsx
  src/pages/flavor/FlavorTest.tsx
  src/pages/myprofile/MyProfileEdit.tsx
  src/pages/thunder/Thunder.tsx
Labels: ✨ Feat, 🎨 Design, 🔧 Change

#16 ✨ Feat: landing페이지 로그인 시 음식추천 컴포넌트 생성
  public/images/kimchiSoup.svg
  public/images/leftArrow.svg
  public/images/rightArrow.svg
  public/images/soyBeanPasteSoup.svg
  src/components/board/BoardCard.tsx
  src/components/flavor/ProgressBar.tsx
  src/components/landing/FirstSection.tsx
  src/components/landing/FoodSection.tsx
  src/components/landing/FoodsCarousel.tsx
  src/components/landing/Footer.tsx
  src/components/landing/ImageWithPlaceHolder.tsx
  src/components/landing/Section.tsx
  src/components/layout/Nav.tsx
  src/components/myprofile/PostNav.tsx
  src/components/thunder/ThunderCard.tsx
  src/data/FoodsCarouselList.ts
  src/pages/Home/Landing.tsx
  src/pages/Home/index.tsx
  src/pages/flavor/FlavorTest.tsx
  src/pages/myprofile/MyProfile.tsx
  src/pages/myprofile/MyProfileBoard.tsx
  src/pages/myprofile/MyProfileThunder.tsx
  src/pages/profile/ProfileId.tsx
  src/pages/thunder/Thunder.tsx
  src/store/store.ts
  src/types/types.ts
  src/utils/formatAppointmentTime.ts
  src/utils/formatCreatedAt.ts
Labels: ✨ Feat, 🎨 Design, ♻️ Refactor, 🔧 Change, 🔥 Edit

#17 ✨ Feat: 소셜 다이닝 게시판 글 작성 페이지 기능 추가
  public/_redirects
  public/images/ThunderChatSend.svg
  src/App.tsx
  src/components/board/BoardCard.tsx
  src/components/board/BoardCommentModal.tsx
  src/components/layout/Header.tsx
  src/components/layout/Nav.tsx
  src/components/thunder/ThunderCalendarModal.tsx
  src/components/thunder/ThunderClockModal.tsx
  src/components/thunder/ThunderCommentModal.tsx
  src/components/thunder/ThunderImageModal.tsx
  src/data/BoardList.tsx
  src/data/meetingList.ts
  src/pages/board/Board.tsx
  src/pages/board/BoardId.tsx
  src/pages/board/BoardPost.tsx
  src/pages/myprofile/MyProfileBoard.tsx
  src/pages/myprofile/MyProfileThunder.tsx
  src/pages/thunder/Thunder.tsx
  src/pages/thunder/ThunderChat.tsx
  src/pages/thunder/ThunderId.tsx
  src/pages/thunder/ThunderPost.tsx
  vite.config.ts
Labels: ✨ Feat, 🔧 Change, 📦 Chore, 🔥 Edit

#18 ✨ Feat: 음식 추천 페이지 개발
  index.html
  package-lock.json
  package.json
  public/images/kimchi.png
  public/images/marker.svg
  public/images/marker2.svg
  public/images/reload.svg
  src/DUMMY_DATA/FOOD_DATA.json
  src/components/common/Input.tsx
  src/components/common/Tag.tsx
  src/components/foods/FoodCard.tsx
  src/components/foods/KakaoMap.tsx
  src/components/layout/Header.tsx
  src/components/layout/Nav.tsx
  src/pages/auth/Signup.tsx
  src/pages/foods/Foods.tsx
  src/pages/foods/FoodsId.tsx
  src/store/foodStore/foodStore.ts
  tailwind.config.js
  tsconfig.json
Labels: 🤡 Test, ✨ Feat, 🔧 Change, 📦 Chore, 🔥 Edit

#19 ✨ Feat: 로그인, 회원가입 API연동
  package-lock.json
  package.json
  src/api/.gitkeep
  src/api/apis/auth.ts
  src/api/util/instance.ts
  src/pages/auth/Signin.tsx
  src/pages/auth/Signup.tsx
  src/utils/.gitkeep
  src/utils/cookie.ts
  src/utils/storage.ts
Labels: ✨ Feat, 🔧 Change, 📦 Chore

#20 ✨ Feat: thunder 목록 api로 수정
  src/api/util/instance.ts
  src/components/landing/FirstSection.tsx
  src/components/landing/FoodSection.tsx
  src/components/landing/FoodsCarousel.tsx
  src/components/thunder/SelectionItem.tsx
  src/components/thunder/ThunderCard.tsx
  src/data/FoodsCarouselList.ts
  src/pages/Home/Landing.tsx
  src/pages/flavor/Flavor.tsx
  src/pages/flavor/FlavorTest.tsx
  src/pages/thunder/Thunder.tsx
  src/store/foodStore/foodStore.ts
  src/types/types.ts
Labels: ✨ Feat

#21 ✨ Feat: flavor test api응답으로 수정
  src/api/util/instance.ts
  src/components/common/Loading.tsx
  src/pages/Home/Landing.tsx
  src/pages/flavor/Flavor.tsx
  src/pages/flavor/FlavorTest.tsx
  src/pages/thunder/Thunder.tsx
Labels: ✨ Feat, ♻️ Refactor, 🔥 Edit

#22 ✨ Feat: 소셜 다이닝, 맛있는 발견 API 연동
  public/images/bobpience_logo2.png
  src/components/board/BoardCard.tsx
  src/components/layout/HeaderLanding.tsx
  src/components/thunder/ThunderCard.tsx
  src/pages/board/Board.tsx
  src/pages/board/BoardId.tsx
  src/pages/board/BoardPost.tsx
  src/pages/thunder/Thunder.tsx
  src/pages/thunder/ThunderChat.tsx
  src/pages/thunder/ThunderId.tsx
  src/pages/thunder/ThunderPost.tsx
Labels: ✨ Feat, 🎨 Design
